# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for chatqna.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: opea/chatqna
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

port: 8888
service:
  type: ClusterIP
  port: 8888

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}

resources: {}

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}

tolerations: []

affinity: {}

# To override values in subchart tgi, vllm-openvino and llm-vllm-uservice
tgi:
  LLM_MODEL_ID: Intel/neural-chat-7b-v3-3

vllm-openvino:
  LLM_MODEL_ID: Intel/neural-chat-7b-v3-3
  enabled: false

llm-vllm-uservice:
  LLM_MODEL_ID: Intel/neural-chat-7b-v3-3

tags:
  tgi: true
  vllm: false

# disable guardrails-usvc by default
# See guardrails-values.yaml for guardrail related options
guardrails-usvc:
  enabled: false

global:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  HUGGINGFACEHUB_API_TOKEN: "insert-your-huggingface-token-here"

  # set modelUseHostPath or modelUsePVC to use model cache.
  modelUseHostPath: ""
  # modelUsePVC: model-volume

  # Enabling HorizontalPodAutoscaler (HPA) will:
  # - Overwrite existing PrometheusAdapter "adapter-config" configMap with ChatQnA specific custom metric queries
  #   for embedding, reranking, tgi services
  # Upstream default configMap:
  #  - https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/deploy/manifests/config-map.yaml
  horizontalPodAutoscaler:
    enabled: false
