# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

image:
  repository: opea/videoqna-ui:latest
  pullPolicy: IfNotPresent
  tag: "latest"

# Endpoint for VideoQnA Backend
videoqnaBackendService: "/v1/videoqna"
# Endpoint for VideoQnA Backend Service health check
videoqnaBackendHealthCheck: "/v1/health_check"

service:
  type: ClusterIP
  port: 5173
