# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vllm-openvino.fullname" . }}-config
  labels:
    {{- include "vllm-openvino.labels" . | nindent 4 }}
data:
  MODEL_ID: {{ .Values.global.LLM_MODEL_ID | quote }}
  PORT: {{ .Values.service.port | quote }}
  HF_TOKEN: {{ .Values.global.HUGGINGFACEHUB_API_TOKEN | quote}}
  VLLM_CPU_KVCACHE_SPACE: {{ .Values.VLLM_CPU_KVCACHE_SPACE | quote }}
  HABANA_VISIBLE_DEVICES : {{ .Values.HABANA_VISIBLE_DEVICES | quote }}
  OMPI_MCA_btl_vader_single_copy_mechanism: {{ .Values.OMPI_MCA_btl_vader_single_copy_mechanism | quote }}
  {{- if .Values.global.HF_ENDPOINT }}
  HF_ENDPOINT: {{ .Values.global.HF_ENDPOINT | quote}}
  {{- end }}
  http_proxy: {{ .Values.global.http_proxy | quote }}
  https_proxy: {{ .Values.global.https_proxy | quote }}
  no_proxy: {{ .Values.global.no_proxy | quote }}
  HABANA_LOGS: "/tmp/habana_logs"
  NUMBA_CACHE_DIR: "/tmp"
  TRANSFORMERS_CACHE: "/tmp/transformers_cache"
  HF_HOME: "/tmp/.cache/huggingface"
  {{- if .Values.MAX_INPUT_LENGTH }}
  MAX_INPUT_LENGTH: {{ .Values.MAX_INPUT_LENGTH | quote }}
  {{- end }}
  {{- if .Values.MAX_TOTAL_TOKENS }}
  MAX_TOTAL_TOKENS: {{ .Values.MAX_TOTAL_TOKENS | quote }}
  {{- end }}
  {{- if .Values.CUDA_GRAPHS }}
  CUDA_GRAPHS: {{ .Values.CUDA_GRAPHS | quote }}
  {{- end }}
