# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vllm-openvino.fullname" . }}
  labels:
    {{- include "vllm-openvino.labels" . | nindent 4 }}
spec:
  {{- if not .Values.global.horizontalPodAutoscaler.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vllm-openvino.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vllm-openvino.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: {{ include "vllm-openvino.fullname" . }}-config
            {{- if .Values.global.extraEnvConfig }}
            - configMapRef:
                name: {{ .Values.global.extraEnvConfig }}
                optional: true
            {{- end }}
          securityContext:
            {{- if .Values.global.modelUseHostPath }}
            {}
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.livenessProbe}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{ end }}
          {{- if .Values.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{ end }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              cd / && \
              python3 -m vllm.entrypoints.openai.api_server \
                --model "{{ .Values.LLM_MODEL_ID }}" \
                --host 0.0.0.0 \
                --port 80
      volumes:
        - name: model-volume
          {{- if .Values.global.modelUsePVC }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.modelUsePVC }}
          {{- else if .Values.global.modelUseHostPath }}
          hostPath:
            path: {{ .Values.global.modelUseHostPath }}
            type: Directory
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.global.horizontalPodAutoscaler.enabled }}
      # extra time to finish processing buffered requests before HPA forcibly terminates pod
      terminationGracePeriodSeconds: 120
      {{- end }}
