# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

{{- if .Values.global.horizontalPodAutoscaler.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vllm-openvino.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "vllm-openvino.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 4s
    port: tgi
    scheme: http
{{- end }}
